version: "3.7"
services:
  db_auth:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  auth:
    build: ./auth
    env_file:
      - ./auth/.env
    ports:
      - "5000:5000"
    depends_on:
      - db_auth

volumes:
  postgres_data: