openapi: "3.0.0"
info:
  version: 1.0.0
  title: User Management API
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User registered successfully
        '400':
          description: Invalid input data
        '409':
          description: Username already exists
  /login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid credentials
  /users/me:
    update:
      summary: Update user details
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_firstname:
                  type: string
                new_lastname:
                  type: string
                new_birth_date:
                  type: string
                  format: date
                new_email:
                  type: string
                  format: email
                new_phone_number:
                  type: string
      responses:
        '200':
          description: Details updated
        '404':
          description: User Not Found
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
